### PR TITLE
excess whitespace fixes

### PR DESCRIPTION
**Pull request by leonardcj**
These trailing whitespaces have a tendency to result in "end whitespace" errors in Pootle.  That is meaningful because ending newline errors also get flagged that way and those can be fatal errors at build time, unlike the cosmetic errors being flagged here.  There is one simple grammatical typo fixed as well.

### CODE REVIEW

**Comment by rachbrooke** [comment]
@leonardcj Could you please update your branch so that it is synced with the master branch? We will be able to commit your changes like that :-) Thanks!

**Comment by ceciliapersson** [comment]
Hello, could you sync again? There's been some more changes to the master. Thanks //Cecilia

**Comment by ceciliapersson** [comment]
@leonardcj Hello again, since I just merged you're first pull request, the master branch and your branch got out of sync. Could you update? Thanks :)

**Comment by rachbrooke** [comment]
@leonardcj Could you please update your branch so that it is synced with the master branch? We will be able to commit your changes like that :-) Thanks!

**Comment by leonardcj** [comment]
updated branch

**Comment by ceciliapersson** [comment]
@leonardcj Could you update your branch again please? Thanks :) Cecilia

**Pull request merged**
