### PR TITLE
Implementation guide interoperability section

### PR DESCRIPTION
**Pull request by PatrickE-Health**
I have created a github branch (ImpGuidelines-InterOp) which is being synched to the server repository. I replaced the “integration.XML” with a new file of the same name and added pictures into the corresponding resource path. Most content that was in the section before is included, some updated or replaced by new contents. It may be useful to think about splitting the different aspects of integration into different sections. But this can be done later once we have advanced with contents.
This has removed all ambiguities, in case of doubt I removed information, which I will complete over the next weeks and then add again. 

Only bottleneck would be a technical check of the formatting (I talked about this a few days ago with Ola and Rachael).  On a local copy I have used Oxygen to produce a PDF export to verify the output. I see that the output diverges from the PDF that I see online   (https://docs.dhis2.org/master/en/implementer/dhis2_implementation_guide.pdf ). Differences are for example different fonts, different size and missing numbering of headlines.

### CODE REVIEW

**Comment by jason-p-pickering** [comment]
@PatrickE-Health thanks for your PR.  Its a bit hard to tell exactly what changed here. I think this may be due to extra line breaks in your file like [here](https://github.com/dhis2/dhis2-docs/pull/694/commits/a67bb55707d251dd28215c1ca3f3558d14fb5979#diff-3067ff1ad54470753d1aabafb7c2029cR2)

Also, the "OLD" file should be removed, if you are updating the content. 

As for the differences in formatting between Oxygen and what DocBook builds, this is expected. You can build the documentation locally. This is discussed [here]( https://docs.dhis2.org/master/en/implementer/html/docs_9.html). 

Usually, you should build the docs locally to be sure nothing has broken. Travis of course will build this as well, but it can help to use Maven to build everything locally first just to be sure, although if you are using Oxygen, then it should also inform you if there are any DocBook errors.

**Comment by PatrickE-Health** [comment]
Hi Jason,

80% of the file contents changed. It is a complete rework of the original
content. Not sure what you mean by extra lines? Is it cleaner to replace
the integration file manually?

The PDF is building fine on Oxygen except some of the formatting (see
attached output). Only one error: Include operation failed, reverting to
fallback. Resource error reading file as XML (href='build.properties').
Reason:
C:\Users\Lenovo14\Dropbox\dhis2-docs\src\docbkx\en\content\bookinfo\build.properties
(The system cannot find the file specified).



In parallel I am also doing the Maven thing. So I installed JDK, extracted
Maven and am executing commands but get confused at this point.

“Just execute the command *mvn clean package* on Windows or on Linux from
the /dhis2-docbook-docs “ .

I don´t see that directory in the local repository. Is the path correct?

Patrick





*From:* Jason Pickering [mailto:notifications@github.com]
*Sent:* Donnerstag, 13. Juli 2017 11:59
*To:* dhis2/dhis2-docs <dhis2-docs@noreply.github.com>
*Cc:* PatrickE-Health <mail@patrickernst.de>; Mention <
mention@noreply.github.com>
*Subject:* Re: [dhis2/dhis2-docs] Imp guidelines inter op (#694)



@PatrickE-Health <https://github.com/patricke-health> thanks for your PR.
Its a bit hard to tell exactly what changed here. I think this may be due
to extra line breaks in your file like here
<https://github.com/dhis2/dhis2-docs/pull/694/commits/a67bb55707d251dd28215c1ca3f3558d14fb5979#diff-3067ff1ad54470753d1aabafb7c2029cR2>

Also, the "OLD" file should be removed, if you are updating the content.

As for the differences in formatting between Oxygen and what DocBook
builds, this is expected. You can build the documentation locally. This is
discussed here
<https://docs.dhis2.org/master/en/implementer/html/docs_9.html>.

Usually, you should build the docs locally to be sure nothing has broken.
Travis of course will build this as well, but it can help to use Maven to
build everything locally first just to be sure, although if you are using
Oxygen, then it should also inform you if there are any DocBook errors.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dhis2/dhis2-docs/pull/694#issuecomment-315016957>, or mute
the thread

**Comment by jason-p-pickering** [comment]
@PatrickE-Health I am going to merge this . I think it will be easier to clean things up once we get it merged.

**Comment by jason-p-pickering** [comment]
@PatrickE-Health 

Seems some images are missing. Could you look at things like

imagedata width="100%" align="center" fileref="../../resources/images/implementation_guide/implementation_steps.png format="PNG"/> 

that image seems to be missing .

**Comment by PatrickE-Health** [comment]
Yes. Other things that are screwed up are some of the headers… Will look at
it



*From:* Jason Pickering [mailto:notifications@github.com]
*Sent:* Donnerstag, 13. Juli 2017 16:38
*To:* dhis2/dhis2-docs <dhis2-docs@noreply.github.com>
*Cc:* PatrickE-Health <mail@patrickernst.de>; Mention <
mention@noreply.github.com>
*Subject:* Re: [dhis2/dhis2-docs] Implementation guide interoperability
section (#694)



@PatrickE-Health <https://github.com/patricke-health>

Seems some images are missing. Could you look at things like

imagedata width="100%" align="center"
fileref="../../resources/images/implementation_guide/implementation_steps.png
format="PNG"/>

that image seems to be missing .

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dhis2/dhis2-docs/pull/694#issuecomment-315080088>, or mute
the thread

**Comment by PatrickE-Health** [comment]
Hi Jason,

I am officially lost here. The images are in the correct directory of my
GitHub Desktop Repository. They show up in my Oxygen PDF build. GitHub does
not show me an option to upload them (supposing it is already on the
server). I cannot access the GitHub Server Branch anymore because Pull
Request is completed and it disappeared. Not managing to install Maven to
test locally.

Images attached.





*From:* Jason Pickering [mailto:notifications@github.com]
*Sent:* Donnerstag, 13. Juli 2017 16:38
*To:* dhis2/dhis2-docs <dhis2-docs@noreply.github.com>
*Cc:* PatrickE-Health <mail@patrickernst.de>; Mention <
mention@noreply.github.com>
*Subject:* Re: [dhis2/dhis2-docs] Implementation guide interoperability
section (#694)



@PatrickE-Health <https://github.com/patricke-health>

Seems some images are missing. Could you look at things like

imagedata width="100%" align="center"
fileref="../../resources/images/implementation_guide/implementation_steps.png
format="PNG"/>

that image seems to be missing .

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dhis2/dhis2-docs/pull/694#issuecomment-315080088>, or mute
the thread

**Comment by jason-p-pickering** [comment]
@PatrickE-Health also, please do not use any section numbers such as `<title><emphasis>1:1</emphasis> integration</title>`.  This will be handled automatically by Docbook at runtime, and should be considered to be dynamic, since chapters may be reordered in the overall book.

**Comment by PatrickE-Health** [comment]
Oups so then I should rename it “One to One – Integration”? The actual
meaning is “1:1” as opposed to “n:n”. tricky



*From:* Jason Pickering [mailto:notifications@github.com]
*Sent:* Donnerstag, 13. Juli 2017 16:46
*To:* dhis2/dhis2-docs <dhis2-docs@noreply.github.com>
*Cc:* PatrickE-Health <mail@patrickernst.de>; Mention <
mention@noreply.github.com>
*Subject:* Re: [dhis2/dhis2-docs] Implementation guide interoperability
section (#694)



@PatrickE-Health <https://github.com/patricke-health> also, please do not
use any section numbers such as <title><emphasis>1:1</emphasis>
integration</title>. This will be handled automatically by Docbook at
runtime, and should be considered to be dynamic, since chapters may be
reordered in the overall book.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dhis2/dhis2-docs/pull/694#issuecomment-315082362>, or mute
the thread

**Comment by jason-p-pickering** [comment]
@PatrickE-Health please update your branch with the updated source code from the main branch. The easiest way to do this is to add an "upstream" branch to your fork. 

`git add remote upstream git@github.com:dhis2/dhis2-docs.git`

Then you can merge from the upstream (main) branch with 

`git pull upstream master`

into your own fork's master (or other) branch. Once you make your changes there locally, you can submit a new pull request. 

Let me know if you have any questions regarding the procedure.

**Pull request merged**
