### PR TITLE
chore: typo

### PR DESCRIPTION
**Pull request by dayures**

### CODE REVIEW

**Review by linadhis2 — APPROVED** [review]
LGTM

**Comment by linadhis2** [comment]
@dayures This typo is likely in docs 38-40 & dev, so if you create PRs to all of them I can review and we can merge :)

**Comment by dayures** [comment]
@linadhis2 in order to do that (PRs for each version), how should I procced? which branches should I send the PR to ?

**Comment by linadhis2** [comment]
> @linadhis2 in order to do that (PRs for each version), how should I procced? which branches should I send the PR to ?

Unfortunately there's no easy way to do that - we need to recreate it for each. What this means is you should change the documentation versions in the same way as you did not for 40, for 38, 39 and master (the versions we currently support + development branch). Let me know if you have troubles and I can create those PRs, too.

**Comment by dayures** [comment]
@linadhis2 I think that I managed to do it. Can you double check it ?

**Comment by linadhis2** [comment]
> @linadhis2 I think that I managed to do it. Can you double check it ?

Yes, thanks a lot! I merged them all, feel free to clean up your branches. It will take a while for it to update the files (usually I check in a day to make sure :)).

**Pull request merged**
