### PR TITLE
Updated Screenshot manage-users-user-roles-and-user-groups.md

### PR DESCRIPTION
**Pull request by SaranshBaniyal**
I wasn't able to update the screenshots for the email invite method, namely the  "dhis2-docs/src/user/resources/images/dhis2UserManual/user_management_invite.png" as it required configuring the SMTP Email setting in System Settings. 
PS:- Please consider adding the hacktober fest label to this PR

### CODE REVIEW

**Comment by SaranshBaniyal** [comment]
@Topener I have submitted the PR. Please have a look

**Review by Topener — APPROVED** [review]
Looks great! Thanks so much for contributing. I've already added the proper hacktoberfest label to this PR so it should count already. Merge will happen soon!

**Comment by SaranshBaniyal** [comment]
@Topener Thanks a lot

**Comment by Philip-Larsen-Donnelly** [comment]
@SaranshBaniyal 

Thanks for your contributions. 

To be honest I was going to reject this PR as it doesn't conform to our [guidelines](https://github.com/dhis2/dhis2-docs#taking-screenshots) for screenshots, which are designed to avoid problems for users with low-resolution screens.
However, although your images are wider than our guidelines, I see that most of the old screenshots they are replacing are even worse :grimacing:, so I will include yours as they are both more up-to-date and also a step in the right direction :+1: 

Thanks again!

**Comment by SaranshBaniyal** [comment]
@Philip-Larsen-Donnelly thanks a lot. I'll try to do better next time. Had a wonderful time working and learning here with you guyz

**Pull request merged**
