### PR TITLE
Tracker doc - misc review and updates

### PR DESCRIPTION
**Pull request by ceciliapersson**

### CODE REVIEW

**Comment by ceciliapersson** [comment]
@jason-p-pickering Could you help me with this conflict? I don't understand why it is there, I haven't edited the build prop file. I've been updating the tracker-doc branch from master on a regular basis to keep it in synch with the master branch. It has worked fine until this evening when I got a strange conflict. 

I can't see any difference between the tracker-doc branch and the master branch, why is there a conflict? Would appreciate you advice.

Content of build prop file:
_tracker-doc branch_
<revhistory  xmlns='http://docbook.org/ns/docbook'><revision><revnumber>2765</revnumber><date>2016-09-29 16:04:24</date><revremark>Version 2.25</revremark></revision></revhistory>

_master branch_
<revhistory  xmlns='http://docbook.org/ns/docbook'><revision><revnumber>2765</revnumber><date>2016-09-29 16:04:24</date><revremark>Version 2.25</revremark></revision></revhistory>

FYI, both Rachael and I have seen this type of files suddenly being flagged as "changed" in the Git Desktop app even though we haven't edit them. I suspect it has something to do with how the Git Desktop app works and sync with GitHub.

**Comment by jason-p-pickering** [comment]
@ceciliapersson I think this was my fault actually. The build.properties file is modified when building the documents locally, but should be ignored when committing. There is  a default build.properties file which is used when building locally, and git is not available. This is to ensure that the docs can be built even when git is not available. 

Anyway, I think I have fixed it now. Lets see if travis builds everything.

**Comment by ceciliapersson** [comment]
@jason-p-pickering ok, thanks for the info and help! :)

**Comment by ceciliapersson** [comment]
@jason-p-pickering I worked :) Merging PR now.

**Pull request merged**
